### ISSUE TITLE
abo-abo is missing

### ISSUE THREAD

**Issue by bymoz089** [freetonik/support-emacs-community-devs#1]
Oleh Krehel aka abo-abo is missing.
He has done really amazing stuff, like ivy, swiper, counsel and I do not know whatnot.

[github](https://github.com/abo-abo)
[homepage](https://oremacs.com/)

**Comment by freetonik** [comment]
Done https://github.com/freetonik/support-emacs-community-devs#oleh-krehel-abo-abo
